local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://por.bcy-p.metalhosts.com/cre-alpha/MvqtrdftrbxcP3ZgGBJb3bK5/ethereum/sepolia

production-testnet:
  cre-cli:
    don-family: "zone-a"
  logging:
    seth-config-path: ""
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://ethereum-rpc.publicnode.com
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://base-sepolia-rpc.publicnode.com
  dev-platform:
    don-id: 4
