local-simulation:
  user-workflow:
    workflow-name: "oracle-court"
  workflow-artifacts:
    workflow-path: "./index.ts"
    config-path: "./config.local.generated.json"

production-testnet:
  user-workflow:
    workflow-name: "oracle-court"
  workflow-artifacts:
    workflow-path: "./index.ts"
    config-path: "./config.generated.json"
